### ISSUE TITLE
panic: No Auth Provider found for name "oidc" when --type helm

### ISSUE THREAD

**Issue by pastukhov** [operator-framework/operator-sdk#1178]
## Bug Report

```
operator-sdk new logstash-operator --type helm --helm-chart stable/logstash
operator-sdk up local

INFO[0000] Running the operator locally.                
INFO[0000] Using namespace default.                     
{"level":"info","ts":1551951667.5239906,"logger":"cmd","msg":"Go Version: go1.10.4"}
{"level":"info","ts":1551951667.5240135,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1551951667.5240204,"logger":"cmd","msg":"Version of operator-sdk: v0.5.0+git"}
{"level":"info","ts":1551951667.5240347,"logger":"cmd","msg":"Watching single namespace.","Namespace":"default"}
panic: No Auth Provider found for name "oidc"

goroutine 1 [running]:
github.com/operator-framework/operator-sdk/vendor/k8s.io/client-go/discovery.NewDiscoveryClientForConfigOrDie(0xc42053c000, 0x0)
        src/github.com/operator-framework/operator-sdk/vendor/k8s.io/client-go/discovery/discovery_client.go:454 +0x65
github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDiscoveryRESTMapper(0xc42053c000, 0xc4206dd9e0, 0x0, 0x0, 0x0)
        src/github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go:35 +0x2f
github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/manager.New(0xc42053c000, 0xc4204d6000, 0x1bfaff8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4207e68b0, ...)
        src/github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go:171 +0x167
github.com/operator-framework/operator-sdk/pkg/helm.Run(0xc4203007e0, 0x0, 0x0)
        src/github.com/operator-framework/operator-sdk/pkg/helm/run.go:72 +0x267
github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/up.upLocalHelm(0x1b1206b, 0x4)
        src/github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/up/local.go:152 +0x5e
github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/up.upLocalFunc(0xc4208aca00, 0x2b69e78, 0x0, 0x0, 0x0, 0x0)
        src/github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/up/local.go:97 +0x24d
github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra.(*Command).execute(0xc4208aca00, 0x2b69e78, 0x0, 0x0, 0xc4208aca00, 0x2b69e78)
        src/github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra/command.go:762 +0x468
github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4207cac80, 0xc4208ad400, 0xc4208acc80, 0xc4208ac780)
        src/github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4207cac80, 0xc42087ff78, 0xc420046178)
        src/github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        src/github.com/operator-framework/operator-sdk/commands/operator-sdk/main.go:24 +0x27
```

**Environment**
* operator-sdk version:
operator-sdk version v0.5.0+git

* Kubernetes version information:

```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"9e4010d067ee4d799330980e62830b06a07296bd", GitTreeState:"clean", BuildDate:"2018-04-26T04:13:21Z", GoVersion:"go1.10.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2+coreos.0", GitCommit:"b427929b2982726eeb64e985bc1ebb41aaa5e095", GitTreeState:"clean", BuildDate:"2018-01-18T22:56:14Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

Helm operator to handle logstash installations

**Comment by LiliC** [comment]
@pastukhov We support Kubernetes clusters from [version 1.11.3+](https://github.com/operator-framework/operator-sdk#prerequisites) onwards, yours seems to be `1.9.2`.

But I think you might have a problem in your operator code, how did you import `oidc`? Not sure have you seen[ this issue](https://github.com/kubernetes/client-go/issues/345#issuecomment-352139468).

**Comment by pastukhov** [comment]
I'm trying to make helm operator and there is no go code at all.
I have seen issue about it.

**Comment by LiliC** [comment]
cc @joelanford as he is more familiar with helm operators.

**Comment by joelanford** [comment]
@pastukhov as @LiliC mentioned, your cluster versions are not supported by the Helm operator, so you will very likely need to upgrade your client and server to at least 1.11.3 to get things working.

To solve the OIDC error, we may need to update the SDK to import the package from the issue @LiliC linked in her comment.

In the meantime, if you have a go development environment setup, you may be able to resolve it by running `operator-sdk migrate`, editing `cmd/manager/main.go` to add the necessary import, and rebuilding your operator using the helm-operator's Go source.
