### ISSUE TITLE
No Auth provider found for name "azure"

### ISSUE THREAD

**Issue by patst** [operator-framework/operator-sdk#1196]
## Bug Report

**What did you do?**
I'm trying to run `operator-sdk up local` to test my developed operator.
The kubernetes cluster is running with Azure AKS and uses RBAC authorization with Azure AD.

**What did you expect to see?**
I'm expecting to be able to use the local operator.

**What did you see instead? Under which circumstances?**
I'm getting this exception after running the `operator-sdk up local` command:

```
operator-sdk up local --kubeconfig=/c/Users/N1122966/.kube/config --namespace=default
INFO[0000] Running the operator locally.INFO[0000] Using namespace default.
{"level":"info","ts":1552380484.646539,"logger":"cmd","msg":"Go Version: go1.11.5"}
{"level":"info","ts":1552380484.6473377,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1552380484.647636,"logger":"cmd","msg":"Version of operator-sdk: v0.5.0+git"}
{"level":"info","ts":1552380484.6478565,"logger":"cmd","msg":"Watching single namespace.","Namespace":"default"}
panic: No Auth Provider found for name "azure"

goroutine 1 [running]:
github.com/operator-framework/operator-sdk/vendor/k8s.io/client-go/discovery.NewDiscoveryClientForConfigOrDie(0xc0000e43c0, 0x0)
        /home/n1122966/go/src/github.com/operator-framework/operator-sdk/vendor/k8s.io/client-go/discovery/discovery_client.go:454 +0x65
github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDiscoveryRESTMapper(0xc0000e43c0, 0xc0003dd050, 0x0, 0x0, 0x0)
        /home/n1122966/go/src/github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go:35 +0x2f
github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/manager.New(0xc0000e43c0, 0xc0000d4000, 0x1c25cc8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0006c2310, ...)
        /home/n1122966/go/src/github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go:171 +0x157
github.com/operator-framework/operator-sdk/pkg/helm.Run(0xc000604980, 0x0, 0x0)
        /home/n1122966/go/src/github.com/operator-framework/operator-sdk/pkg/helm/run.go:72 +0x262
github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/up.upLocalHelm(0x1b3c75f, 0x4)
        /home/n1122966/go/src/github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/up/local.go:152 +0x5e
github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/up.upLocalFunc(0xc000892a00, 0xc000604c00, 0x0, 0x2, 0x0, 0x0)
        /home/n1122966/go/src/github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/up/local.go:97 +0x241
github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra.(*Command).execute(0xc000892a00, 0xc000604bc0, 0x2, 0x2, 0xc000892a00, 0xc000604bc0)
        /home/n1122966/go/src/github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra/command.go:762 +0x473
github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000790c80, 0xc000893400, 0xc000892c80, 0xc000892780)
        /home/n1122966/go/src/github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra.(*Command).Execute(0xc000790c80, 0xc000879f88, 0xc0000ac058)
        /home/n1122966/go/src/github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        /home/n1122966/go/src/github.com/operator-framework/operator-sdk/commands/operator-sdk/main.go:24 +0x27
``` 

**Environment**
* operator-sdk version:
0.5.0

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

Azure AKS Version 12.6

* Are you writing your operator in ansible, helm, or go?

helm

**Possible Solution**
Add the `"plugin/pkg/client/auth/azure",` from `client-go` package in the Gopkg.lock to import the Azure auth provider?

**Comment by joelanford** [comment]
@patst Thanks for the bug report. We received a similar report about the Helm operator with the `oidc` plugin, so we'll definitely look into it. If you have a Go environment setup, you might find the [workaround I mentioned in #1178](https://github.com/operator-framework/operator-sdk/issues/1178#issuecomment-470807971) helpful.

**Comment by patst** [comment]
Thanks for the mentioned workaround. I got it working and looking forward to see it fixed!
