### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by gosoon** [operator-framework/operator-sdk#1579]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

```
$ operator-sdk add api --api-version=yun/v1 --kind=Kubernetes
INFO[0000] Generating api version yun/v1 for kind Kubernetes.
INFO[0001] Created pkg/apis/yun/v1/kubernetes_types.go
INFO[0001] Created pkg/apis/addtoscheme_yun_v1.go
INFO[0001] Created pkg/apis/yun/v1/register.go
INFO[0001] Created pkg/apis/yun/v1/doc.go
INFO[0001] Created deploy/crds/yun_v1_kubernetes_cr.yaml
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/operator-framework/operator-sdk/internal/pkg/scaffold.(*CRD).CustomRender(0xc0001ba6e0, 0x2cca8c0, 0x41db7c0, 0x4ab60f8, 0xc0001ba6e0, 0x1)
	src/github.com/operator-framework/operator-sdk/internal/pkg/scaffold/crd.go:113 +0xbac
github.com/operator-framework/operator-sdk/internal/pkg/scaffold.(*Scaffold).doRender(0xc000addcf8, 0xc0001962d0, 0x26, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00069cc81, 0x1c, ...)
	src/github.com/operator-framework/operator-sdk/internal/pkg/scaffold/scaffold.go:228 +0x16c
github.com/operator-framework/operator-sdk/internal/pkg/scaffold.(*Scaffold).doFile(0xc000addcf8, 0x2c4f2c0, 0xc0001ba6e0, 0x0, 0x0)
	src/github.com/operator-framework/operator-sdk/internal/pkg/scaffold/scaffold.go:198 +0x230
github.com/operator-framework/operator-sdk/internal/pkg/scaffold.(*Scaffold).Execute(0xc000addcf8, 0xc00095dc68, 0xc000addc98, 0x6, 0x6, 0x0, 0x0)
	src/github.com/operator-framework/operator-sdk/internal/pkg/scaffold/scaffold.go:163 +0x103
github.com/operator-framework/operator-sdk/cmd/operator-sdk/add.apiRun(0xc000188280, 0xc0005da280, 0x0, 0x2, 0x0, 0x0)
	src/github.com/operator-framework/operator-sdk/cmd/operator-sdk/add/api.go:107 +0x4d2
github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra.(*Command).execute(0xc000188280, 0xc0005da240, 0x2, 0x2, 0xc000188280, 0xc0005da240)
	src/github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra/command.go:762 +0x465
github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0005bcc80, 0x2c53720, 0xc0000fcd00, 0x0)
	src/github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	src/github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra/command.go:800
main.main()
	src/github.com/operator-framework/operator-sdk/cmd/operator-sdk/main.go:80 +0x4ce
```

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-sdk version:  operator-sdk version: v0.8.1, commit: 33b3bfe10176f8647f5354516fff29dea42b6342

* go version:

* Kubernetes version information:

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

**Possible Solution**

**Additional context**

**Comment by LiliC** [comment]
@gosoon this happens because your `api-version` is not valid, I agree we should not panic but currently for you to fix the error, you need to provide a valid api-version, from the docs:

> --api-version string   Kubernetes APIVersion that has a format of $GROUP_NAME/$VERSION (e.g app.example.com/v1alpha1)
