### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by satishrao84** [operator-framework/operator-sdk#1994]
## Bug Report

**What did you do?**

Followed the readme to create new project

```
bash-3.2$ operator-sdk new couchbase-cluster-operator
INFO[0000] Creating new Go operator 'couchbase-cluster-operator'. 
INFO[0000] Created go.mod                               
INFO[0000] Created tools.go                             
INFO[0000] Created cmd/manager/main.go                  
INFO[0000] Created build/Dockerfile                     
INFO[0000] Created build/bin/entrypoint                 
INFO[0000] Created build/bin/user_setup                 
INFO[0000] Created deploy/service_account.yaml          
INFO[0000] Created deploy/role.yaml                     
INFO[0000] Created deploy/role_binding.yaml             
INFO[0000] Created deploy/operator.yaml                 
INFO[0000] Created pkg/apis/apis.go                     
INFO[0000] Created pkg/controller/controller.go         
INFO[0000] Created version/version.go                   
INFO[0000] Created .gitignore                           
INFO[0000] Validating project                           
go: finding github.com/operator-framework/operator-sdk master
go: finding github.com/prometheus/prometheus d3245f15022551c6fc8281766ea62db4d71e2747
INFO[0006] Project validation successful.               
INFO[0006] Project creation complete.                   

bash-3.2$ cd couchbase-cluster-operator/
bash-3.2$ GO111MODULE=on GOROOT='/usr/local/go' operator-sdk add api --api-version=couchbase.com/v1 --kind=CouchbaseCluster
INFO[0000] Generating api version couchbase.com/v1 for kind CouchbaseCluster. 
INFO[0000] Created pkg/apis/couchbase/group.go          
panic: runtime error: index out of range

goroutine 66 [running]:
golang.org/x/tools/imports.(*moduleResolver).scan.func1(0xc0007f5950, 0x23, 0x4, 0xc00084bda0, 0x42)
	pkg/mod/golang.org/x/tools@v0.0.0-20190408170212-12dd9f86f350/imports/mod.go:254 +0x9df
golang.org/x/tools/internal/gopathwalk.(*walker).walk(0xc000500380, 0xc00084bda0, 0x52, 0x0, 0xc00084bda0, 0x52)
	pkg/mod/golang.org/x/tools@v0.0.0-20190408170212-12dd9f86f350/internal/gopathwalk/walk.go:175 +0xf5
golang.org/x/tools/internal/fastwalk.(*walker).onDirEnt(0xc0007e37d0, 0xc000834a50, 0x42, 0xc000730590, 0xf, 0xc000000000, 0x0, 0x0)
	pkg/mod/golang.org/x/tools@v0.0.0-20190408170212-12dd9f86f350/internal/fastwalk/fastwalk.go:168 +0xbb
golang.org/x/tools/internal/fastwalk.readDir(0xc000834a50, 0x42, 0xc00083de88, 0x0, 0x0)
	pkg/mod/golang.org/x/tools@v0.0.0-20190408170212-12dd9f86f350/internal/fastwalk/fastwalk_unix.go:68 +0x212
golang.org/x/tools/internal/fastwalk.(*walker).walk(0xc0007e37d0, 0xc000834a50, 0x42, 0x1, 0x1, 0x0)
	pkg/mod/golang.org/x/tools@v0.0.0-20190408170212-12dd9f86f350/internal/fastwalk/fastwalk.go:195 +0x6a
golang.org/x/tools/internal/fastwalk.(*walker).doWork(0xc0007e37d0, 0xc000810330)
	pkg/mod/golang.org/x/tools@v0.0.0-20190408170212-12dd9f86f350/internal/fastwalk/fastwalk.go:134 +0x14d
created by golang.org/x/tools/internal/fastwalk.Walk
	pkg/mod/golang.org/x/tools@v0.0.0-20190408170212-12dd9f86f350/internal/fastwalk/fastwalk.go:81 +0x21d
```

**What did you see instead? Under which circumstances?**
I reinstalled GoLang, reinstalled OPerator-sdk, explicitly set GOROOT... tried everything. Cannot get past this index out of bounds exception. 

**Environment**
* operator-sdk version: operator-sdk version: v0.10.0, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170

* go version: go version go1.13.1 darwin/amd64

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}```

* Kubernetes cluster kind: 
docker-desktop
* Are you writing your operator in ansible, helm, or go?
go
**Possible Solution**
<!--- Only if you have suggestions on a fix for the bug -->

**Additional context**
Add any other context about the problem here.

**Comment by camilamacedo86** [comment]
Hi @satishrao84, 

The Go Version 1.13 is not supported yet.  Could you please check it with +12?
I am closing this one since shows that this issue faced is because of the go version, however, please feel free to re-open if required.

**Comment by satishrao84** [comment]
I installed Go version 1.12 and reinstalled operator-sdk. 

```
bash-3.2$ go  version
go version go1.12.10 darwin/amd64
```

Still see the panic

> bash-3.2$ GO111MODULE=on GOROOT='/usr/local/go' operator-sdk add api --api-version=couchbase.com/v1 --kind=CouchbaseCluster
> FATA[0000] must run command in project root dir: project structure requires build/Dockerfile 
> bash-3.2$ cd couchbase-cluster-operator/
> bash-3.2$ GO111MODULE=on GOROOT='/usr/local/go' operator-sdk add api --api-version=couchbase.com/v1 --kind=CouchbaseCluster
> INFO[0000] Generating api version couchbase.com/v1 for kind CouchbaseCluster. 
> INFO[0000] Created pkg/apis/couchbase/group.go          
> panic: runtime error: index out of range
> 
> goroutine 120 [running]:
> golang.org/x/tools/internal/imports.(*moduleResolver).scan.func1(0xc0006e49f0, 0x23, 0x4, 0xc0000e2480, 0x42)
> 	pkg/mod/golang.org/x/tools@v0.0.0-20190624180213-70d37148ca0c/internal/imports/mod.go:254 +0x9e7
> golang.org/x/tools/internal/gopathwalk.(*walker).walk(0xc00082e180, 0xc0000e2480, 0x52, 0x0, 0xc0000e2480, 0x52)
> 	pkg/mod/golang.org/x/tools@v0.0.0-20190624180213-70d37148ca0c/internal/gopathwalk/walk.go:175 +0xf5
> golang.org/x/tools/internal/fastwalk.(*walker).onDirEnt(0xc0001ff590, 0xc000054820, 0x42, 0xc000209130, 0xf, 0xc000000000, 0x0, 0x0)
> 	pkg/mod/golang.org/x/tools@v0.0.0-20190624180213-70d37148ca0c/internal/fastwalk/fastwalk.go:168 +0xbb
> golang.org/x/tools/internal/fastwalk.readDir(0xc000054820, 0x42, 0xc00070de88, 0x0, 0x0)
> 	pkg/mod/golang.org/x/tools@v0.0.0-20190624180213-70d37148ca0c/internal/fastwalk/fastwalk_unix.go:68 +0x212
> golang.org/x/tools/internal/fastwalk.(*walker).walk(0xc0001ff590, 0xc000054820, 0x42, 0x1, 0x1, 0x0)
> 	pkg/mod/golang.org/x/tools@v0.0.0-20190624180213-70d37148ca0c/internal/fastwalk/fastwalk.go:195 +0x6a
> golang.org/x/tools/internal/fastwalk.(*walker).doWork(0xc0001ff590, 0xc000824680)
> 	pkg/mod/golang.org/x/tools@v0.0.0-20190624180213-70d37148ca0c/internal/fastwalk/fastwalk.go:134 +0x14d
> created by golang.org/x/tools/internal/fastwalk.Walk
> 	pkg/mod/golang.org/x/tools@v0.0.0-20190624180213-70d37148ca0c/internal/fastwalk/fastwalk.go:81 +0x21d


Below is `go env`

> bash-3.2$ go env
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/Users/sanupin/Library/Caches/go-build"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="darwin"
> GOOS="darwin"
> GOPATH="/Users/sanupin/go-workspace"
> GOPROXY=""
> GORACE=""
> GOROOT="/usr/local/go"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
> GCCGO="gccgo"
> CC="clang"
> CXX="clang++"
> CGO_ENABLED="1"
> GOMOD="/Users/sanupin/go.mod"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
>

**Comment by satishrao84** [comment]
How can I re-open this issue?

**Comment by jmccormick2001** [comment]
Hi,  I just tried the following commands on a linux box and it worked for me,
can you run these same commands and see the results?

  operator-sdk new couchbase-cluster-operator --repo=github.com/example-inc/couchbase-operator
  cd couchbase-cluster-operator/
  operator-sdk add api --api-version=cache.example.com/v1alpha1 --kind=Couchbase

**Comment by satishrao84** [comment]
Hi,

I am on MacOS, doesn't work for me. It used to till about a week ago - maybe with the latest version of operator this has started problems for me. 

```
bash-3.2$ export GO111MODULE=on


bash-3.2$ operator-sdk new couchbase-cluster-operator --repo=github.com/example-inc/couchbase-operator
INFO[0000] Creating new Go operator 'couchbase-cluster-operator'. 
INFO[0000] Created go.mod                               
INFO[0000] Created tools.go                             
INFO[0000] Created cmd/manager/main.go                  
INFO[0000] Created build/Dockerfile                     
INFO[0000] Created build/bin/entrypoint                 
INFO[0000] Created build/bin/user_setup                 
INFO[0000] Created deploy/service_account.yaml          
INFO[0000] Created deploy/role.yaml                     
INFO[0000] Created deploy/role_binding.yaml             
INFO[0000] Created deploy/operator.yaml                 
INFO[0000] Created pkg/apis/apis.go                     
INFO[0000] Created pkg/controller/controller.go         
INFO[0000] Created version/version.go                   
INFO[0000] Created .gitignore                           
INFO[0000] Validating project                           
go: finding github.com/operator-framework/operator-sdk master
go: finding k8s.io/api kubernetes-1.14.1
go: finding k8s.io/apiextensions-apiserver kubernetes-1.14.1
go: finding k8s.io/apimachinery kubernetes-1.14.1
go: finding k8s.io/client-go kubernetes-1.14.1
go: finding k8s.io/cloud-provider kubernetes-1.14.1
INFO[0015] Project validation successful.               
INFO[0015] Project creation complete.     

              
bash-3.2$ cd couchbase-cluster-operator/


bash-3.2$ operator-sdk add api --api-version=cache.example.com/v1alpha1 --kind=Couchbase
INFO[0000] Generating api version cache.example.com/v1alpha1 for kind Couchbase. 
INFO[0000] Created pkg/apis/cache/group.go              
panic: runtime error: index out of range

goroutine 104 [running]:
golang.org/x/tools/internal/imports.(*moduleResolver).scan.func1(0xc00071a660, 0x23, 0x4, 0xc00092d140, 0x42)
	pkg/mod/golang.org/x/tools@v0.0.0-20190624180213-70d37148ca0c/internal/imports/mod.go:254 +0x9e7
golang.org/x/tools/internal/gopathwalk.(*walker).walk(0xc0000ec400, 0xc00092d140, 0x52, 0x0, 0xc00092d140, 0x52)
	pkg/mod/golang.org/x/tools@v0.0.0-20190624180213-70d37148ca0c/internal/gopathwalk/walk.go:175 +0xf5
golang.org/x/tools/internal/fastwalk.(*walker).onDirEnt(0xc0004dfcb0, 0xc000337c70, 0x42, 0xc00034bcc0, 0xf, 0xc000000000, 0x0, 0x0)
	pkg/mod/golang.org/x/tools@v0.0.0-20190624180213-70d37148ca0c/internal/fastwalk/fastwalk.go:168 +0xbb
golang.org/x/tools/internal/fastwalk.readDir(0xc000337c70, 0x42, 0xc000853e88, 0x0, 0x0)
	pkg/mod/golang.org/x/tools@v0.0.0-20190624180213-70d37148ca0c/internal/fastwalk/fastwalk_unix.go:68 +0x212
golang.org/x/tools/internal/fastwalk.(*walker).walk(0xc0004dfcb0, 0xc000337c70, 0x42, 0x1, 0x1, 0x0)
	pkg/mod/golang.org/x/tools@v0.0.0-20190624180213-70d37148ca0c/internal/fastwalk/fastwalk.go:195 +0x6a
golang.org/x/tools/internal/fastwalk.(*walker).doWork(0xc0004dfcb0, 0xc0000519e0)
	pkg/mod/golang.org/x/tools@v0.0.0-20190624180213-70d37148ca0c/internal/fastwalk/fastwalk.go:134 +0x14d
created by golang.org/x/tools/internal/fastwalk.Walk
	pkg/mod/golang.org/x/tools@v0.0.0-20190624180213-70d37148ca0c/internal/fastwalk/fastwalk.go:81 +0x21d
```

**Comment by camilamacedo86** [comment]
Hi @satishrao84, 

I am using a MacOSX and all work well. Let's re-check all do step by step as follows. 

## Ensure that you have all pre-requirements and versions.

- Check the go version: go version v1.12+. (go version)
**- Check the mercurial version 3.9+.(hg version)** > Ensure that it is installed. 
- Access to a Kubernetes v1.11.3+ cluster.
- Check kubectl version v1.11.3+.(kubectl version)
- Check the docker version 17.03+(docker version)

**Now, run the command without "--repo=github.com/example-inc/couchbase-operator" please.** 

$ export GO111MODULE=on
$ operator-sdk new couchbase-cluster-operator
$ cd couchbase-cluster-operator
$ operator-sdk add api --api-version=cache.example.com/v1alpha1 --kind=Couchbase

Please, let me know if you after that all worked and we can close it.

**Comment by satishrao84** [comment]
Hi Camila,

Are you using minikube or docker-desktop? Still getting the same error.

```
bash-3.2$ operator-sdk new couchbase-cluster-operator
INFO[0000] Creating new Go operator 'couchbase-cluster-operator'. 
INFO[0000] Created go.mod                               
INFO[0000] Created tools.go                             
INFO[0000] Created cmd/manager/main.go                  
INFO[0000] Created build/Dockerfile                     
INFO[0000] Created build/bin/entrypoint                 
INFO[0000] Created build/bin/user_setup                 
INFO[0000] Created deploy/service_account.yaml          
INFO[0000] Created deploy/role.yaml                     
INFO[0000] Created deploy/role_binding.yaml             
INFO[0000] Created deploy/operator.yaml                 
INFO[0000] Created pkg/apis/apis.go                     
INFO[0000] Created pkg/controller/controller.go         
INFO[0000] Created version/version.go                   
INFO[0000] Created .gitignore                           
INFO[0000] Validating project                           
go: finding github.com/operator-framework/operator-sdk master
go: finding k8s.io/api kubernetes-1.14.1
go: finding k8s.io/apiextensions-apiserver kubernetes-1.14.1
go: finding k8s.io/apimachinery kubernetes-1.14.1
go: finding k8s.io/client-go kubernetes-1.14.1
go: finding k8s.io/cloud-provider kubernetes-1.14.1
go: downloading github.com/operator-framework/operator-sdk v0.10.1-0.20191003162215-1801b81d5400
go: extracting github.com/operator-framework/operator-sdk v0.10.1-0.20191003162215-1801b81d5400
INFO[0012] Project validation successful.               
INFO[0012] Project creation complete.     
              
bash-3.2$ cd couchbase-cluster-operator/

bash-3.2$ operator-sdk add api --api-version=cache.example.com/v1alpha1 --kind=CouchbaseCluster
INFO[0000] Generating api version cache.example.com/v1alpha1 for kind CouchbaseCluster. 
INFO[0000] Created pkg/apis/cache/group.go              
panic: runtime error: index out of range

goroutine 116 [running]:
golang.org/x/tools/internal/imports.(*moduleResolver).scan.func1(0xc0006f3410, 0x23, 0x4, 0xc00092bd40, 0x42)
	pkg/mod/golang.org/x/tools@v0.0.0-20190624180213-70d37148ca0c/internal/imports/mod.go:254 +0x9e7
golang.org/x/tools/internal/gopathwalk.(*walker).walk(0xc000327a80, 0xc00092bd40, 0x52, 0x0, 0xc00092bd40, 0x52)
	pkg/mod/golang.org/x/tools@v0.0.0-20190624180213-70d37148ca0c/internal/gopathwalk/walk.go:175 +0xf5
golang.org/x/tools/internal/fastwalk.(*walker).onDirEnt(0xc0007ab6b0, 0xc0005ae000, 0x42, 0xc000053630, 0xf, 0xc000000000, 0x0, 0x0)
	pkg/mod/golang.org/x/tools@v0.0.0-20190624180213-70d37148ca0c/internal/fastwalk/fastwalk.go:168 +0xbb
golang.org/x/tools/internal/fastwalk.readDir(0xc0005ae000, 0x42, 0xc000795e88, 0x0, 0x0)
	pkg/mod/golang.org/x/tools@v0.0.0-20190624180213-70d37148ca0c/internal/fastwalk/fastwalk_unix.go:68 +0x212
golang.org/x/tools/internal/fastwalk.(*walker).walk(0xc0007ab6b0, 0xc0005ae000, 0x42, 0x1, 0x1, 0x0)
	pkg/mod/golang.org/x/tools@v0.0.0-20190624180213-70d37148ca0c/internal/fastwalk/fastwalk.go:195 +0x6a
golang.org/x/tools/internal/fastwalk.(*walker).doWork(0xc0007ab6b0, 0xc00032f090)
	pkg/mod/golang.org/x/tools@v0.0.0-20190624180213-70d37148ca0c/internal/fastwalk/fastwalk.go:134 +0x14d
created by golang.org/x/tools/internal/fastwalk.Walk
	pkg/mod/golang.org/x/tools@v0.0.0-20190624180213-70d37148ca0c/internal/fastwalk/fastwalk.go:81 +0x21d
```

kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

docker version:

```bash-3.2$ docker --version
Docker version 19.03.1, build 74b1e89```

**Comment by satishrao84** [comment]
Works after downgrading to 0.9.x version. 

```
bash-3.2$ GOROOT="/usr/local/go" operator-sdk add api --api-version=couchbase.com/v1 --kind=CouchbaseCluster
INFO[0000] Generating api version couchbase.com/v1 for kind CouchbaseCluster. 
INFO[0000] Created pkg/apis/couchbase/group.go          
INFO[0002] Created pkg/apis/couchbase/v1/couchbasecluster_types.go 
INFO[0002] Created pkg/apis/addtoscheme_couchbase_v1.go 
INFO[0002] Created pkg/apis/couchbase/v1/register.go    
INFO[0002] Created pkg/apis/couchbase/v1/doc.go         
INFO[0002] Created deploy/crds/couchbase_v1_couchbasecluster_cr.yaml 
INFO[0011] Created deploy/crds/couchbase_v1_couchbasecluster_crd.yaml 
INFO[0011] Running deepcopy code-generation for Custom Resource group versions: [couchbase:[v1], ] 
INFO[0019] Code-generation complete.                    
INFO[0019] Running OpenAPI code-generation for Custom Resource group versions: [couchbase:[v1], ] 
INFO[0034] Created deploy/crds/couchbase_v1_couchbasecluster_crd.yaml 
INFO[0034] Code-generation complete.                    
INFO[0034] API generation complete.     
```
