### ISSUE TITLE
Segfault when adding api

### ISSUE THREAD

**Issue by lulf** [operator-framework/operator-sdk#2049]
## Bug Report

**What did you do?**
Followed the quickstart guide with latest operator-sdk release. Got the the point of generating an api.

**What did you expect to see?**
That api was generated

**What did you see instead? Under which circumstances?**

Segfault.

```
[lulf@pteppic lulf]$ mkdir -p $HOME/projects/example-inc/

[lulf@pteppic lulf]$ cd $HOME/projects/example-inc/

[lulf@pteppic example-inc]$ export GO111MODULE=on

[lulf@pteppic example-inc]$ operator-sdk new app-operator --repo github.com/example-inc/app-operator
INFO[0000] Creating new Go operator 'app-operator'.
INFO[0000] Created go.mod
INFO[0000] Created tools.go
INFO[0000] Created cmd/manager/main.go
INFO[0000] Created build/Dockerfile
INFO[0000] Created build/bin/entrypoint
INFO[0000] Created build/bin/user_setup
INFO[0000] Created deploy/service_account.yaml
INFO[0000] Created deploy/role.yaml
INFO[0000] Created deploy/role_binding.yaml
INFO[0000] Created deploy/operator.yaml
INFO[0000] Created pkg/apis/apis.go
INFO[0000] Created pkg/controller/controller.go
INFO[0000] Created version/version.go
INFO[0000] Created .gitignore
INFO[0000] Validating project
go: finding github.com/operator-framework/operator-sdk v0.10.x
INFO[0003] Project validation successful.
INFO[0003] Project creation complete.

[lulf@pteppic example-inc]$ cd app-operator

[lulf@pteppic app-operator]$ operator-sdk add api --api-version=app.example.com/v1alpha1 --kind=AppService
INFO[0000] Generating api version app.example.com/v1alpha1 for kind AppService.
INFO[0000] Created pkg/apis/app/group.go
INFO[0000] Created pkg/apis/app/v1alpha1/appservice_types.go
INFO[0000] Created pkg/apis/addtoscheme_app_v1alpha1.go
INFO[0000] Created pkg/apis/app/v1alpha1/register.go
INFO[0000] Created pkg/apis/app/v1alpha1/doc.go
INFO[0000] Created deploy/crds/app_v1alpha1_appservice_cr.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xce8dc5]

goroutine 1 [running]:
k8s.io/gengo/parser.(*Builder).AddDirRecursive(0xc0002aa870, 0xc00041b920, 0x2c, 0x2, 0x2)
        pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/parser/parse.go:229 +0xb5
sigs.k8s.io/controller-tools/pkg/crd/generator.(*Generator).Do(0xc000641760, 0x0, 0x0)
        pkg/mod/sigs.k8s.io/controller-tools@v0.0.0-20190411181648-9d55346c2bde/pkg/crd/generator/generator.go:126 +0x3ac
github.com/operator-framework/operator-sdk/internal/pkg/scaffold.(*CRD).CustomRender(0xc0000f58c0, 0x2114520, 0x341bfc0, 0x7f428a4b3620, 0xc0000f58c0, 0x1)
        /Users/haseeb/work/module-projects/operator-sdk/internal/pkg/scaffold/crd.go:102 +0x27e
github.com/operator-framework/operator-sdk/internal/pkg/scaffold.(*Scaffold).doRender(0xc000641cf8, 0xc00041b860, 0x2c, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000551b00, 0x23, ...)
        /Users/haseeb/work/module-projects/operator-sdk/internal/pkg/scaffold/scaffold.go:222 +0x16c
github.com/operator-framework/operator-sdk/internal/pkg/scaffold.(*Scaffold).doFile(0xc000641cf8, 0x209a2c0, 0xc0000f58c0, 0x0, 0x0)
        /Users/haseeb/work/module-projects/operator-sdk/internal/pkg/scaffold/scaffold.go:192 +0x230
github.com/operator-framework/operator-sdk/internal/pkg/scaffold.(*Scaffold).Execute(0xc000641cf8, 0xc00078bc68, 0xc000641c98, 0x6, 0x6, 0x0, 0x0)
        /Users/haseeb/work/module-projects/operator-sdk/internal/pkg/scaffold/scaffold.go:157 +0x103
github.com/operator-framework/operator-sdk/cmd/operator-sdk/add.apiRun(0xc000364780, 0xc0002ce820, 0x0, 0x2, 0x0, 0x0)
        /Users/haseeb/work/module-projects/operator-sdk/cmd/operator-sdk/add/api.go:118 +0x542
github.com/spf13/cobra.(*Command).execute(0xc000364780, 0xc0002ce7e0, 0x2, 0x2, 0xc000364780, 0xc0002ce7e0)
        pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc000364280, 0x209d6e0, 0xc000696800, 0x0)
        pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
        /Users/haseeb/work/module-projects/operator-sdk/cmd/operator-sdk/main.go:85 +0x50f


```

**Environment**

* OS: Fedora 30

* operator-sdk version: 0.10.1

* go version: go1.12.10 linux/amd64

**Additional context**

**Comment by fengxsong** [comment]
similar issue with the newest release v1.11.0
```
➜ operator-sdk add api --api-version=apps.ppmon.io/v1alpha1 --kind=Project
INFO[0000] Generating api version apps.ppmon.io/v1alpha1 for kind Project.
INFO[0000] Created pkg/apis/apps/v1alpha1/project_types.go
INFO[0000] Created pkg/apis/addtoscheme_apps_v1alpha1.go
INFO[0000] Created deploy/crds/apps.ppmon.io_v1alpha1_project_cr.yaml
INFO[0000] Created deploy/crds/apps.ppmon.io_projects_crd.yaml
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [apps:[v1alpha1], ]
F1012 08:36:12.251848   32157 deepcopy.go:885] Hit an unsupported type invalid type for invalid type, from ./pkg/apis/apps/v1alpha1.Project
goroutine 1 [running]:
k8s.io/klog.stacks(0xc0012e8800, 0xc000b920e0, 0x8c, 0xdc)
	pkg/mod/k8s.io/klog@v0.3.3/klog.go:855 +0xb1
k8s.io/klog.(*loggingT).output(0x430d8a0, 0xc000000003, 0xc000518000, 0x4117360, 0xb, 0x375, 0x0)
	pkg/mod/k8s.io/klog@v0.3.3/klog.go:806 +0x2d9
k8s.io/klog.(*loggingT).printf(0x430d8a0, 0x3, 0x2b45a09, 0x2a, 0xc000d9ccb0, 0x3, 0x3)
	pkg/mod/k8s.io/klog@v0.3.3/klog.go:705 +0x14e
k8s.io/klog.Fatalf(...)
	pkg/mod/k8s.io/klog@v0.3.3/klog.go:1256
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).doStruct(0xc000edcc00, 0xc0001e80b0, 0xc000cdb950)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/examples/deepcopy-gen/generators/deepcopy.go:885 +0x7bf
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).generateFor(0xc000edcc00, 0xc0001e80b0, 0xc000cdb950)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/examples/deepcopy-gen/generators/deepcopy.go:695 +0xc5
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).GenerateType(0xc000edcc00, 0xc000922720, 0xc0001e80b0, 0x2e48fe0, 0xc00128cda0, 0x0, 0x2b1888b)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/examples/deepcopy-gen/generators/deepcopy.go:608 +0xe86
k8s.io/gengo/generator.(*Context).executeBody(0xc000922720, 0x2e45a40, 0xc000744720, 0x2ec4ae0, 0xc000edcc00, 0x60, 0x10)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/generator/execute.go:304 +0x11d
k8s.io/gengo/generator.(*Context).ExecutePackage(0xc000922540, 0x0, 0x0, 0x2e9af40, 0xc000edcb00, 0x0, 0x0)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/generator/execute.go:265 +0xbf7
k8s.io/gengo/generator.(*Context).ExecutePackages(0xc000922540, 0x0, 0x0, 0xc0007c8e30, 0x1, 0x1, 0x0, 0xc000a52860)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/generator/execute.go:51 +0xc5
k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc0003ea780, 0xc000d9d638, 0x2ae7ca7, 0x6, 0x2bec840, 0xc000a52800, 0x18)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/args/args.go:194 +0x2d7
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.deepcopyGen(0xc0007469c0, 0x3a, 0xc000ad32a0, 0x1, 0x1, 0x18, 0xc000d9d7d8)
	/Users/haseeb/work/module-projects/operator-sdk/cmd/operator-sdk/internal/genutil/k8s.go:95 +0x4d2
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.K8sCodegen.func1(0xc0007469c0, 0x3a, 0xc0007469c0, 0x3a)
	/Users/haseeb/work/module-projects/operator-sdk/cmd/operator-sdk/internal/genutil/k8s.go:54 +0x50
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.generateWithHeaderFile(0xc00123fdc0, 0x0, 0x0)
	/Users/haseeb/work/module-projects/operator-sdk/cmd/operator-sdk/internal/genutil/genutil.go:46 +0x178
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.K8sCodegen(0xc0005fb880, 0xc000058004)
	/Users/haseeb/work/module-projects/operator-sdk/cmd/operator-sdk/internal/genutil/k8s.go:55 +0x4c0
github.com/operator-framework/operator-sdk/cmd/operator-sdk/add.apiRun(0xc00040c780, 0xc00022ef40, 0x0, 0x2, 0x0, 0x0)
	/Users/haseeb/work/module-projects/operator-sdk/cmd/operator-sdk/add/api.go:140 +0x6e9
github.com/spf13/cobra.(*Command).execute(0xc00040c780, 0xc00022ef20, 0x2, 0x2, 0xc00040c780, 0xc00022ef20)
	pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc000329900, 0x2e4a7c0, 0xc0005f7600, 0x0)
	pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/Users/haseeb/work/module-projects/operator-sdk/cmd/operator-sdk/main.go:85 +0x50f
```

**Comment by Mengkzhaoyun** [comment]
the same

**Comment by fengxsong** [comment]
> **Environment**
> 
> * OS: Ubuntu 18.04
> * operator-sdk version: 0.11.0
> * go version: go version go1.13.1 linux/amd64
> 
> the same problem

this [answer](https://github.com/operator-framework/operator-sdk/issues/1854#issuecomment-525132306) may help.

**Comment by Mengkzhaoyun** [comment]
@fengxsong  , thank you , after set GOROOT in ENV , the bug fixed.

**Comment by camilamacedo86** [comment]
Also, note that the 1.13 is not supported yet. 
You need to use 1.12+ for now. 
I am closing this one since you already found the solution.

**Comment by lulf** [comment]
Shouldn’t the fact that GOROOT must be set, be documented somewhere? Seems like a common problem you would run into in a clean development environment.
