### ISSUE TITLE
No Auth Provider found for name "oidc"

### ISSUE THREAD

**Issue by ernoaapa** [operator-framework/operator-sdk#289]
Hi,
I'm having problem to run locally if I use `oidc` authentication.

#### Kube config:
```yaml
- name: my-mail@gmail.com
  user:
    auth-provider:
      name: oidc
      config:
          # .... configs ....
```

#### Error: 
```shell
$ operator-sdk up local                                                                                                                                                                    (master)
panic: No Auth Provider found for name "oidc"

goroutine 1 [running]:
github.com/ernoaapa/operator-test/vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1alpha1.NewForConfigOrDie(0xc4203bb680, 0xc4203261e0)
	/Users/ernoaapa/Code/go/src/github.com/ernoaapa/operator-test/vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1alpha1/admissionregistration_client.go:58 +0x65
github.com/ernoaapa/operator-test/vendor/k8s.io/client-go/kubernetes.NewForConfigOrDie(0xc4203bb680, 0x0)
	/Users/ernoaapa/Code/go/src/github.com/ernoaapa/operator-test/vendor/k8s.io/client-go/kubernetes/clientset.go:529 +0x49
github.com/ernoaapa/operator-test/vendor/github.com/operator-framework/operator-sdk/pkg/k8sclient.mustNewKubeClientAndConfig(0x1012ae8, 0x10, 0x1b66620)
	/Users/ernoaapa/Code/go/src/github.com/ernoaapa/operator-test/vendor/github.com/operator-framework/operator-sdk/pkg/k8sclient/client.go:104 +0x6a
github.com/ernoaapa/operator-test/vendor/github.com/operator-framework/operator-sdk/pkg/k8sclient.init.0()
	/Users/ernoaapa/Code/go/src/github.com/ernoaapa/operator-test/vendor/github.com/operator-framework/operator-sdk/pkg/k8sclient/client.go:43 +0x34
exit status 2
Error: failed to run operator locally: exit status 1
```

Any ideas?

**Comment by rithujohn191** [comment]
Hi @ernoaapa ,

I have successfully been able to run  the `operator-sdk up` command with a Kube Config that uses oidc as the `auth-provider`.

Is the kube config being used valid? i.e can you perform other cluster operations using the same kube config. Also have you tried to run the operator [as a pod inside a Kubernetes cluster](https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#1-run-as-pod-inside-a-kubernetes-cluster) using the same kube config?

**Comment by rithujohn191** [comment]
Hi @ernoaapa ,

If this is no longer an issue I would like to close it out. Please do let us know.

**Comment by rithujohn191** [comment]
Closing this for now. Please reopen if you have any concerns.
