### ISSUE TITLE
NameError: name 'watch' is not defined in k8s_scale module from ansible community collection

### ISSUE THREAD

**Issue by stiller-leser** [operator-framework/operator-sdk#3500]
## Type of question

operator-sdk and ansible galaxy collections

## Question

**What did you do?**
```
- name: 'Scaling system down'
  k8s_scale:
    api_version: v1
    kind: Deployment
    name: "MySystem"
    namespace: "{{ meta.namespace }}"
    current_replicas: 1
    replicas: 0
```

**What did you expect to see?**

A downscaled deployment

**What did you see instead? Under which circumstances?**

```
The full traceback is:
Traceback (most recent call last):
  File "/Users/myUser/.ansible/tmp/ansible-tmp-1595519051.600846-44537-174633508382038/AnsiballZ_k8s_scale.py", line 102, in <module>
    _ansiballz_main()
  File "/Users/myUser/.ansible/tmp/ansible-tmp-1595519051.600846-44537-174633508382038/AnsiballZ_k8s_scale.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/myUser/.ansible/tmp/ansible-tmp-1595519051.600846-44537-174633508382038/AnsiballZ_k8s_scale.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.clustering.k8s.k8s_scale', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/folders/z7/hh2kjvns02l1xkr4b38w1fgm0000gn/T/ansible_k8s_scale_payload_mcy559iy/ansible_k8s_scale_payload.zip/ansible/modules/clustering/k8s/k8s_scale.py", line 129, in <module>
  File "/var/folders/z7/hh2kjvns02l1xkr4b38w1fgm0000gn/T/ansible_k8s_scale_payload_mcy559iy/ansible_k8s_scale_payload.zip/ansible/modules/clustering/k8s/k8s_scale.py", line 125, in main
  File "/var/folders/z7/hh2kjvns02l1xkr4b38w1fgm0000gn/T/ansible_k8s_scale_payload_mcy559iy/ansible_k8s_scale_payload.zip/ansible/module_utils/k8s/scale.py", line 141, in execute_module
  File "/var/folders/z7/hh2kjvns02l1xkr4b38w1fgm0000gn/T/ansible_k8s_scale_payload_mcy559iy/ansible_k8s_scale_payload.zip/ansible/module_utils/k8s/scale.py", line 170, in scale
  File "/var/folders/z7/hh2kjvns02l1xkr4b38w1fgm0000gn/T/ansible_k8s_scale_payload_mcy559iy/ansible_k8s_scale_payload.zip/ansible/module_utils/k8s/scale.py", line 192, in _create_stream
NameError: name 'watch' is not defined
```

**Environment**
* operator-sdk version:

  operator-sdk version: "v0.19.0", commit: "8e28aca60994c5cb1aec0251b85f0116cc4c9427", kubernetes version: "v1.18.2", go version: "go1.14.4 darwin/amd64"

* Kubernetes version information:

  Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

self operated

**Additional context**
Using k8s_scale module

Hi,

I am trying to scale a deployment using the `k8s_scale` ansible community module from https://github.com/ansible-collections/community.kubernetes. However it fails with `NameError: name 'watch' is not defined`. This error is due to an old version of the ansible-collection as it is fixed now (https://github.com/ansible-collections/community.kubernetes/commit/beebe98ce63f295f63e1e9e767922584d3816cb4). I tried to update it locally using `ansible-galaxy collection install community.kubernetes`. However, running `operator-sdk run local --watches-file watches_local.yaml --ansible-verbosity=4` still produces the error. Is it taking the ansible-collections from somewhere else? Removing everything in ~/.ansible and /tmp does not seem to help. I also do not have a `requirements.txt` in my operator.

Best regards,
stiller-leser

**Comment by stiller-leser** [comment]
Did some more testing this morning. Adding a requirement.yml does not help. The error also occurs after building the operator image with `operator-sdk build` and deploying it into the cluster.

**Comment by stiller-leser** [comment]
I assume this could be solved by using `community.kubernetes.k8s` instead of `k8s`?

**Comment by asmacdo** [comment]
You should use the fully qualified collection name to invoke the module, see below. If there is something wrong with the module, you'll want to file an upstream ticket: https://github.com/ansible-collections/community.kubernetes/issues/new/choose

```
- name: 'Scaling system down'
  community.kubernetes.k8s_scale:
    api_version: v1
    kind: Deployment
    name: "MySystem"
    namespace: "{{ meta.namespace }}"
    current_replicas: 1
    replicas: 0
```

Closing for now, feel free to reopen if this does not solve your problem.

**Comment by asmacdo** [comment]
> Question that is kinda related: I am downscaling a deployment that is controlled by another CR. It seems downscaling the deployment does not resonate in the other CR and it tries to bring it up again. Hence, my downscaling seems to be instantly corrected. Is this assumption right? If so, how could this be archieved?

Could you open a new issue for this? I'm not quite clear on what you are trying to do.

**Comment by stiller-leser** [comment]
Hi,

thanks for getting back to me. Switiching to the community collections worked. A bit confusing though - as depending on which documentation you look - there's only `k8s`. 

Regarding my second question, just ignore it - I figured it out 👍
