### ISSUE TITLE
Operator sdk v1.0.0: Reconcile function gets no namespace if watching cluster-scoped CRD

### ISSUE THREAD

**Issue by aceeric** [operator-framework/operator-sdk#3804]
Following along with the tutorial:
```
$ operator-sdk version
operator-sdk version: "v1.0.0", commit: "d7d5e0cd6cf5468bb66e0849f08fda5bf557f4fa", kubernetes version: "v1.18.2", go version: "go1.13.11 linux/amd64", GOOS: "linux", GOARCH: "amd64"

$ oc whoami
kube:admin

$ cd $(mktemp -d)

$ operator-sdk init\
 --domain abcde.net\
 --project-name foo-project\
 --repo github.com/example-inc/memcached-operator

$ operator-sdk create api --group=qqqqq --version=v1alpha1 --kind=Zzzzz --resource=true --controller=true --namespaced=false

$ make install

$ kubectl create namespace deleteme
namespace/deleteme created

$ kubectl apply -f config/samples/qqqqq_v1alpha1_zzzzz.yaml -n deleteme
zzzzz.qqqqq.abcde.net/zzzzz-sample created
```

So far - all according to the quick start. Now, edit edit controllers/zzzzz_controller.go and put a panic in the generated `Reconcile` method to surface the error:
```
...
func (r *ZzzzzReconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
	_ = context.Background()
	_ = r.Log.WithValues("zzzzz", req.NamespacedName)

	if req.Namespace == "" {
		panic("no namespace")
	}

	return ctrl.Result{}, nil
}
...
```
Then:
```
$ make run
...
E0828 11:11:13.876711   25684 runtime.go:76] Observed a panic: no namespace
goroutine 453 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x13eb320, 0x17c67e0)
...
```
If this operator needed to create secondary resources, it would not be able to without a namespace.

Edit config/crd/bases/qqqqq.abcde.net_zzzzzes.yaml CRD and change it from `Cluster` to `Namespaced`:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: zzzzzes.qqqqq.abcde.net
spec:
  group: qqqqq.abcde.net
  names:
    kind: Zzzzz
    listKind: ZzzzzList
    plural: zzzzzes
    singular: zzzzz
  scope: Namespaced
...
```
Then:
```
$ kubectl delete crd/zzzzzes.qqqqq.abcde.net
customresourcedefinition.apiextensions.k8s.io "zzzzzes.qqqqq.abcde.net" deleted

$ kubectl apply -f config/crd/bases/qqqqq.abcde.net_zzzzzes.yaml

$ kubectl apply -f config/samples/qqqqq_v1alpha1_zzzzz.yaml -n deleteme

$ make run
...
go fmt ./...
go vet ./...
...
go run ./main.go
I0828 11:23:29.822124   30147 request.go:621] Throttling request took 1.044233966s, request: GET:https://api.crc.testing:6443/apis/machineconfiguration.openshift.io/v1?timeout=32s
2020-08-28T11:23:31.774-0400	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": ":8080"}
2020-08-28T11:23:31.774-0400	INFO	setup	starting manager
2020-08-28T11:23:31.774-0400	INFO	controller-runtime.manager	starting metrics server	{"path": "/metrics"}
2020-08-28T11:23:31.774-0400	INFO	controller	Starting EventSource	{"reconcilerGroup": "qqqqq.abcde.net", "reconcilerKind": "Zzzzz", "controller": "zzzzz", "source": "kind source: /, Kind="}
2020-08-28T11:23:31.874-0400	INFO	controller	Starting Controller	{"reconcilerGroup": "qqqqq.abcde.net", "reconcilerKind": "Zzzzz", "controller": "zzzzz"}
2020-08-28T11:23:31.874-0400	INFO	controller	Starting workers	{"reconcilerGroup": "qqqqq.abcde.net", "reconcilerKind": "Zzzzz", "controller": "zzzzz", "worker count": 1}
2020-08-28T11:23:31.874-0400	DEBUG	controller	Successfully Reconciled	{"reconcilerGroup": "qqqqq.abcde.net", "reconcilerKind": "Zzzzz", "controller": "zzzzz", "name": "zzzzz-sample", "namespace": "deleteme"}
```

Observe - no panic - the `Reconcile` method now receives a namespace. So the question is - what needs to be done to configure the controller to receive a namespace when its `Reconciler` function is called by the controller runtime if the controller is watching cluster-scoped CRDs?

This was performed on Code Ready Containers 13 but I suspect that is not particularly relevant:
```
$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://api.crc.testing:6443
kubernetes v1.18.3+8b0a82f
```

**Comment by joelanford** [comment]
@aceeric I'm guessing you may have figured this out since you closed this, but in case anyone else has this same question, the reason you aren't getting a namespace in the request for cluster-scoped resources is because cluster-scoped resources don't belong to any namespace.

If you need your cluster-scoped resource to drive some behavior in a particular namespace (or set of namespaces) you'll have to derive that information from other fields of the resource (e.g. a namespace field in the spec or a label selector to select namespaces based on their labels)

**Comment by aceeric** [comment]
Yes I finally understood that and you are correct - quietly closed the issue. Thanks.
