### ISSUE TITLE
controller-runtime client's 'List' API generates "odd number of arguments passed as key-value pairs for logging" 

### ISSUE THREAD

**Issue by mohansitaram** [operator-framework/operator-sdk#3860]
#### What did you do?

I am a golang/operator-sdk newbie trying to implement an operator for PV management that use the 'Local' PV type. The controller watches for a CRD to be created and labels the Nodes with the name contained in the CRD. I am trying fetch the nodes using the `client` package in `controller-runtime`  like so (I am pasting only the relevant lines in the snippet):
```
import         "sigs.k8s.io/controller-runtime/pkg/client"
...
type LocalPVReconciler struct {
        Client client.Client
        Log    logr.Logger
        Scheme *runtime.Scheme
}
....

func (r *LocalPVReconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
...
        nodeList := &corev1.NodeList{}
        listOpts := []client.ListOption{}
        log.Info("Listing nodes")
        err = r.Client.List(ctx, nodeList, listOpts...)
        if err != nil {
                log.Error(err, "Failed to list nodes")
                return ctrl.Result{}, err 
        }   

```

#### What did you expect to see?

I expected the list of Nodes to be fetched from the API server. 

#### What did you see instead? Under which circumstances?

When I create the CRD , the Reconcile loop gets triggered successfully but the pod crashes. From kubectl logs on the operator pod:

```
2020-09-08T00:37:29.000Z        INFO    controller      Starting EventSource    {"reconcilerGroup": "uhana.vmware.my.domain", "reconcilerKind": "LocalPV", "controller": "localpv",}
2020-09-08T00:37:29.000Z        DEBUG   controller-runtime.manager.events       Normal  {"object": {"kind":"ConfigMap","namespace":"default","name":"75f10c09.my.domain","uid":"7c6}
2020-09-08T00:37:29.100Z        INFO    controller      Starting EventSource    {"reconcilerGroup": "uhana.vmware.my.domain", "reconcilerKind": "LocalPV", "controller": "localpv",}
2020-09-08T00:37:29.201Z        INFO    controller      Starting Controller     {"reconcilerGroup": "uhana.vmware.my.domain", "reconcilerKind": "LocalPV", "controller": "localpv"}
2020-09-08T00:37:29.201Z        INFO    controller      Starting workers        {"reconcilerGroup": "uhana.vmware.my.domain", "reconcilerKind": "LocalPV", "controller": "localpv",}
2020-09-08T00:37:29.201Z        INFO    controllers.LocalPV     Received request        {"localpv": "default/local-pv-test"}
2020-09-08T00:37:29.201Z        INFO    controllers.LocalPV     Fetching localpv instance       {"localpv": "default/local-pv-test"}
2020-09-08T00:37:29.201Z        INFO    controllers.LocalPV     Sent API request to fetch instance. Checking result..   {"localpv": "default/local-pv-test"}
2020-09-08T00:37:29.201Z        INFO    controllers.LocalPV     Listing nodes   {"localpv": "default/local-pv-test"}
2020-09-08T00:37:29.302Z        DPANIC  controllers.LocalPV     odd number of arguments passed as key-value pairs for logging   {"localpv": "default/local-pv-test", "ignored key":}
github.com/go-logr/zapr.handleFields
        /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:106
github.com/go-logr/zapr.(*infoLogger).Info
        /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:70
gitlab.eng.vmware.com/core-build/uhana_piran/controllers.(*LocalPVReconciler).Reconcile
        /workspace/controllers/localpv_controller.go:85
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
        /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90
E0908 00:37:29.302830       1 runtime.go:76] Observed a panic: odd number of arguments passed as key-value pairs for logging
goroutine 325 [running]:
```
I am suspicious about the `List` API because debug messages right below the above code are not getting printed. I tried the `List` API on a different resource (corev1.PodList) and hit the same error. 

#### Environment

**Operator type:**

 /language go 

**Kubernetes cluster type:**

vanilla.  v1.17.6

`$ operator-sdk version`

operator-sdk version: "v1.0.0", commit: "d7d5e0cd6cf5468bb66e0849f08fda5bf557f4fa", kubernetes version: "v1.18.2", go version: "go1.13.11 linux/amd64", GOOS: "linux", GOARCH: "amd6
4

`$ go version` (if language is Go)

go version go1.14.4 linux/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:2}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:3}

#### Additional context

Here is the CRD instance that triggers the reconcile loop

```
kubectl describe localpv
Name:         local-pv-test
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version: ***/v1alpha1
Kind:         LocalPV
Metadata:
  Creation Timestamp:  2020-09-07T23:42:54Z
  Generation:          1
  Resource Version:    1999678
  Self Link:           /apis/***/v1alpha1/namespaces/default/localpvs/local-pv-test
  UID:                 0ff59818-500c-4283-a354-87f0b0dc8101
Spec:
  Instances:  1
  Name:       local-pv-test
  Size:       3Gi
Events:       <none>

```

**Comment by mohansitaram** [comment]
Closing this as this is due to incorrect usage of `go-logr/logr`. I had a line that calls the logger like this:

`log.Info("Nodes are ", nodeList.Items())`

..which doesn't work. Still figuring out how the formatting works with logr but safe to say that its not a problem with the `List` API.
