### ISSUE TITLE
Go Operator-SDK: manager pod restarts when applying sample memcached yaml to Minikube with kubectl and fails in CrashBackLoop

### ISSUE THREAD

**Issue by renczesstefan** [operator-framework/operator-sdk#4993]
#### What did you do?

I tried to create a Memcache example project using Golang and operator-sdk. As Kubernetes I am using Minikube and I have installed kubectl too. I am developing the project using WSL 2 as make and other Linux commands are not available on Windows 10. I followed the tutorial of [operator-sdk for Go](https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/ ), builded image to quay.io and deployed to minikube local cluster. After deploying the operator manager I tried to apply the modified sample yaml of `kind: Memcached` provided in `config/samples/ ` directory. I modified the `size` attribute to value of 3.

#### What did you expect to see?

I expect to see 3 freshly generated pods using the kubectl get pods command.

#### What did you see instead? Under which circumstances?

After applying the sample yaml, when I display the info about the pods, I see that the original manager is seems to be restarted (I think this will be the problem) and I see the following line after getting some info about pods:
`memcached-operator-controller-manager-65d6779cf8-rpp8s   1/2     Error    1          7m51s`

After displaying logs of that pods manager container I see the following error:

```
2021-06-17T09:43:36.990Z        INFO    controller-runtime.metrics      metrics server is starting to listen    {"addr": "127.0.0.1:8080"}
2021-06-17T09:43:36.990Z        INFO    setup   starting manager
I0617 09:43:36.990787       1 leaderelection.go:243] attempting to acquire leader lease default/86f835c3.example.com...
2021-06-17T09:43:36.990Z        INFO    controller-runtime.manager      starting metrics server {"path": "/metrics"}
I0617 09:43:54.445297       1 leaderelection.go:253] successfully acquired lease default/86f835c3.example.com
2021-06-17T09:43:54.445Z        INFO    controller-runtime.manager.controller.memcached Starting EventSource    {"reconciler group": "cache.example.com", "reconciler kind": "Memcached", "source": "kind source: /, Kind="}
2021-06-17T09:43:54.446Z        DEBUG   controller-runtime.manager.events       Normal  {"object": {"kind":"ConfigMap","namespace":"default","name":"86f835c3.example.com","uid":"79bd3c0f-2fce-4f6b-b3ff-b6bfadb9520c","apiVersion":"v1","resourceVersion":"9651"}, "reason": "LeaderElection", "message": "memcached-operator-controller-manager-65d6779cf8-rpp8s_f2d5a237-0b0c-4f3e-aa8e-59804921af0c became leader"}
2021-06-17T09:43:54.446Z        DEBUG   controller-runtime.manager.events       Normal  {"object": {"kind":"Lease","namespace":"default","name":"86f835c3.example.com","uid":"6b76b0ad-58d8-4435-a2c1-0a007545f228","apiVersion":"coordination.k8s.io/v1","resourceVersion":"9652"}, "reason": "LeaderElection", "message": "memcached-operator-controller-manager-65d6779cf8-rpp8s_f2d5a237-0b0c-4f3e-aa8e-59804921af0c became leader"}
2021-06-17T09:43:54.546Z        INFO    controller-runtime.manager.controller.memcached Starting EventSource    {"reconciler group": "cache.example.com", "reconciler kind": "Memcached", "source": "kind source: /, Kind="}
2021-06-17T09:43:54.648Z        INFO    controller-runtime.manager.controller.memcached Starting Controller     {"reconciler group": "cache.example.com", "reconciler kind": "Memcached"}
2021-06-17T09:43:54.648Z        INFO    controller-runtime.manager.controller.memcached Starting workers        {"reconciler group": "cache.example.com", "reconciler kind": "Memcached", "worker count": 1}
E0617 09:43:54.648732       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 249 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1570ea0, 0x222e220)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:48 +0x86
panic(0x1570ea0, 0x222e220)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/example/memcached-operator/controllers.(*MemcachedReconciler).Reconcile(0xc000495740, 0x1901258, 0xc0004b0330, 0xc000522399, 0x7, 0xc000522380, 0x10, 0xc0004b0330, 0xc000030000, 0x15ee500, ...)
        /workspace/controllers/memcached_controller.go:57 +0xbc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0004b9ea0, 0x19011b0, 0xc0003c0000, 0x15bb540, 0xc0004b2140)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004b9ea0, 0x19011b0, 0xc0003c0000, 0xc000028e00)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2(0x19011b0, 0xc0003c0000)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
        /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000028f50)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00069ff50, 0x18d2700, 0xc0004b02a0, 0xc0003c0001, 0xc0000f8660)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000028f50, 0x3b9aca00, 0x0, 0x97cf01, 0xc0000f8660)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x19011b0, 0xc0003c0000, 0xc0004f23d0, 0x3b9aca00, 0x0, 0x1)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x19011b0, 0xc0003c0000, 0xc0004f23d0, 0x3b9aca00)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:213 +0x40d
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1465e3c]
goroutine 249 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:55 +0x109
panic(0x1570ea0, 0x222e220)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/example/memcached-operator/controllers.(*MemcachedReconciler).Reconcile(0xc000495740, 0x1901258, 0xc0004b0330, 0xc000522399, 0x7, 0xc000522380, 0x10, 0xc0004b0330, 0xc000030000, 0x15ee500, ...)
        /workspace/controllers/memcached_controller.go:57 +0xbc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0004b9ea0, 0x19011b0, 0xc0003c0000, 0x15bb540, 0xc0004b2140)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004b9ea0, 0x19011b0, 0xc0003c0000, 0xc000028e00)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2(0x19011b0, 0xc0003c0000)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
        /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000028f50)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00069ff50, 0x18d2700, 0xc0004b02a0, 0xc0003c0001, 0xc0000f8660)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000028f50, 0x3b9aca00, 0x0, 0x97cf01, 0xc0000f8660)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x19011b0, 0xc0003c0000, 0xc0004f23d0, 0x3b9aca00, 0x0, 0x1)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x19011b0, 0xc0003c0000, 0xc0004f23d0, 0x3b9aca00)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:213 +0x40d
```

However, when I run the operator using `make install run` on my host, it works fine with the following logs:

`
2021-06-17T11:45:17.072+0200    INFO    controller-runtime.metrics      metrics server is starting to listen
 {"addr": ":8080"}
2021-06-17T11:45:17.079+0200    INFO    setup   starting manager
2021-06-17T11:45:17.080+0200    INFO    controller-runtime.manager      starting metrics server {"path": "/metrics"}
2021-06-17T11:45:17.080+0200    INFO    controller-runtime.manager.controller.memcached Starting EventSource
 {"reconciler group": "cache.example.com", "reconciler kind": "Memcached", "source": "kind source: /, Kind="}
2021-06-17T11:45:17.189+0200    INFO    controller-runtime.manager.controller.memcached Starting EventSource
 {"reconciler group": "cache.example.com", "reconciler kind": "Memcached", "source": "kind source: /, Kind="}
2021-06-17T11:45:17.298+0200    INFO    controller-runtime.manager.controller.memcached Starting Controller
 {"reconciler group": "cache.example.com", "reconciler kind": "Memcached"}
2021-06-17T11:45:17.298+0200    INFO    controller-runtime.manager.controller.memcached Starting workers
 {"reconciler group": "cache.example.com", "reconciler kind": "Memcached", "worker count": 2}
`

After applying the new sample yaml to the local host, it works fine too and creates the new Deployments with the following log addition to the previous one:

`
2021-06-17T11:47:55.521+0200    INFO    controller-runtime.manager.controller.memcached Creating a new Deployment      {"reconciler group": "cache.example.com", "reconciler kind": "Memcached", "name": "memcached-sample", "namespace": "default", "Deployment.Namespace": "default", "Deployment.Name": "memcached-sample"}
`

I think there I am doing something wrong in case using the Minikube claster.

#### Environment
**Operator type:**

/language go

**Kubernetes cluster type:**

Minikube

`$ operator-sdk version`

'operator-sdk version: "v1.8.0", commit: "d3bd87c6900f70b7df618340e1d63329c7cd651e", kubernetes version: "1.20.2", go version: "go1.16.4", GOOS: "linux", GOARCH: "amd64"'

`$ go version` (if language is Go)

go version go1.15.10 linux/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by varshaprasad96** [comment]
@renczesstefan this maybe similar to https://github.com/operator-framework/operator-sdk/issues/4966. You may have to use the controller code from the latest release branch. The documentation was updated recently.
