### ISSUE TITLE
ocp 4.6 doc controller code panic on ocp 4.6 cluster

### ISSUE THREAD

**Issue by essie-chiang** [operator-framework/operator-sdk#5421]
#### What did you do?

Follow the openshift 4.6 to build and deploy operator
https://docs.openshift.com/container-platform/4.6/operators/operator_sdk/osdk-getting-started.html

#### What did you expect to see?

create CR success with new deployment, controller manager no error

#### What did you see instead? Under which circumstances?
controller manager error below:
`I1130 03:26:21.194319  216939 request.go:665] Waited for 1.048572949s due to client-side throttling, not priority and fairness, request: GET:https://c104-e.us-south.containers.cloud.ibm.com:32598/apis/operator.openshift.io/v1?timeout=32s
2021-11-30T03:26:23.432-0800	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": ":8080"}
2021-11-30T03:26:23.432-0800	INFO	setup	starting manager
2021-11-30T03:26:23.435-0800	INFO	starting metrics server	{"path": "/metrics"}
2021-11-30T03:26:23.435-0800	INFO	controller.memcached	Starting EventSource	{"reconciler group": "cache.example.com", "reconciler kind": "Memcached", "source": "kind source: /, Kind="}
2021-11-30T03:26:23.435-0800	INFO	controller.memcached	Starting EventSource	{"reconciler group": "cache.example.com", "reconciler kind": "Memcached", "source": "kind source: /, Kind="}
2021-11-30T03:26:23.435-0800	INFO	controller.memcached	Starting Controller	{"reconciler group": "cache.example.com", "reconciler kind": "Memcached"}
2021-11-30T03:26:23.637-0800	INFO	controller.memcached	Starting workers	{"reconciler group": "cache.example.com", "reconciler kind": "Memcached", "worker count": 1}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x14fea7c]

goroutine 386 [running]:
github.com/essie-chiang/memcached-operator/controllers.(*MemcachedReconciler).Reconcile(0xc0004b44e0, 0x19ff338, 0xc0000a4270, 0xc0005acc00, 0x19, 0xc000312e60, 0x10, 0xc0000a4270, 0xc0000a41b0, 0xc000717db0, ...)
	/root/essie_dir/memcached-operator/controllers/memcached_controller.go:51 +0xbc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc000598c80, 0x19ff338, 0xc0000a41b0, 0xc0005acc00, 0x19, 0xc000312e60, 0x10, 0xc0000a4100, 0x0, 0x0, ...)
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:114 +0x247
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000598c80, 0x19ff290, 0xc0003b3d80, 0x168d020, 0xc0004be020)
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:311 +0x305
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000598c80, 0x19ff290, 0xc0003b3d80, 0xc000664700)
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc0003c8da0, 0xc000598c80, 0x19ff290, 0xc0003b3d80)
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:227 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:223 +0x425
exit status 2
make: *** [Makefile:97: run] Error 1`

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

OpenShift
`$ operator-sdk version`
operator-sdk version
operator-sdk version: "v1.15.0", commit: "f6326e832a8a5e5453d0ad25e86714a0de2c0fc8", kubernetes version: "1.21", go version: "go1.16.10", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)
 go version
go version go1.16.4 linux/amd64

`$ kubectl version`

kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"2b525e8d2647a41e686bc7da5b7430667a13953e", GitTreeState:"clean", BuildDate:"2021-08-20T22:06:30Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+d5ed12c", GitCommit:"d5ed12c2580a64bf7125514c06435b4144a77e31", GitTreeState:"clean", BuildDate:"2021-09-17T23:43:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

**Comment by essie-chiang** [comment]
code to verify 

https://github.com/essie-chiang/memcached-operator/blob/master/controllers/memcached_controller.go
