### ISSUE TITLE
Unable to Create Deployment for Memcached example using operator-sdk - Controller pod is in crashloopbackoff

### ISSUE THREAD

**Issue by ipsita-npg** [operator-framework/operator-sdk#6006]
referring this guide to create deployment and CR for memcached  using operator-sdk
https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/
https://github.com/operator-framework/operator-sdk/tree/master/testdata/go/v3/memcached-operator

operator-sdk version: operator-sdk version: "v1.10.1-ocp", commit: "bd668f80fdf6a02698335a6c1278bd421477d236", kubernetes version: "v1.21", go version: "go1.16.6", GOOS: "linux", GOARCH: "amd64"
Go version:go1.16.6

CRD is being created :
kubectl get customresourcedefinitions.apiextensions.k8s.io | grep memcached
memcacheds.cache.example.com                          2022-08-26T05:53:50Z

default                  example1-controller-manager-7cd7bbb8f9-mwfxr                 1/2     CrashLoopBackOff   45 (3m15s ago)     3h43m

smartedge-open@esi64:~$ kubectl get memcacheds.cache.example.com
NAME               AGE
memcached-sample   3h45m

kubectl logs -f example1-controller-manager-7cd7bbb8f9-mwfxr -c manager
2022-08-26T09:34:39.410Z        INFO    controller-runtime.metrics      metrics server is starting to listen    {"addr": "127.0.0.1:8080"}
2022-08-26T09:34:39.410Z        INFO    setup   starting manager
I0826 09:34:39.411067       1 leaderelection.go:243] attempting to acquire leader lease default/de587cb0.example.com...
2022-08-26T09:34:39.411Z        INFO    controller-runtime.manager      starting metrics server {"path": "/metrics"}
I0826 09:34:57.767726       1 leaderelection.go:253] successfully acquired lease default/de587cb0.example.com
2022-08-26T09:34:57.767Z        DEBUG   controller-runtime.manager.events       Normal  {"object": {"kind":"ConfigMap","namespace":"default","name":"de587cb0.example.com","uid":"ef69efad-210d-4183-a1bf-b72a7825763b","apiVersion":"v1","resourceVersion":"24137625"}, "reason": "LeaderElection", "message": "example1-controller-manager-7cd7bbb8f9-mwfxr_595d9825-94f4-47d3-bd88-4c1e633e0759 became leader"}
2022-08-26T09:34:57.768Z        DEBUG   controller-runtime.manager.events       Normal  {"object": {"kind":"Lease","namespace":"default","name":"de587cb0.example.com","uid":"0d4536c1-76a7-4dd3-928d-437c8fe2a075","apiVersion":"coordination.k8s.io/v1","resourceVersion":"24137626"}, "reason": "LeaderElection", "message": "example1-controller-manager-7cd7bbb8f9-mwfxr_595d9825-94f4-47d3-bd88-4c1e633e0759 became leader"}
2022-08-26T09:34:57.768Z        INFO    controller-runtime.manager.controller.memcached Starting EventSource    {"reconciler group": "cache.example.com", "reconciler kind": "Memcached", "source": "kind source: /, Kind="}
2022-08-26T09:34:57.768Z        INFO    controller-runtime.manager.controller.memcached Starting EventSource    {"reconciler group": "cache.example.com", "reconciler kind": "Memcached", "source": "kind source: /, Kind="}
2022-08-26T09:34:57.768Z        INFO    controller-runtime.manager.controller.memcached Starting Controller     {"reconciler group": "cache.example.com", "reconciler kind": "Memcached"}
2022-08-26T09:34:58.052Z        INFO    controller-runtime.manager.controller.memcached Starting workers        {"reconciler group": "cache.example.com", "reconciler kind": "Memcached", "worker count": 1}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x14f8c3c]

goroutine 516 [running]:
example1/controllers.(*MemcachedReconciler).Reconcile(0xc000a19c80, 0x19f79b8, 0xc000646390, 0xc0006ba889, 0x7, 0xc0006ba870, 0x10, 0xc000646390, 0xc000030000, 0x16c2000, ...)
        /workspace/controllers/memcached_controller.go:58 +0xbc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000249180, 0x19f7910, 0xc00059e400, 0x16885e0, 0xc0001b75c0)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000249180, 0x19f7910, 0xc00059e400, 0x18aa500)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc0005b5fd0, 0xc000249180, 0x19f7910, 0xc00059e400)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:210 +0x425

**Comment by everettraven** [comment]
Hi @ipsita-npg , thanks for raising this issue! One thing I noticed is that the version of `operator-sdk` that you are using is `v1.10.1-ocp`. Have you tried running through this again with the latest release?

**Comment by varshaprasad96** [comment]
This looks like a nil pointer error: `panic: runtime error: invalid memory address or nil pointer dereference` while starting the controller. Could you please share your reconciler code or your project.
