### ISSUE TITLE
Receiving an error during make deploy "panic: runtime error: invalid memory address or nil pointer dereference "

### ISSUE THREAD

**Issue by sanmaym** [operator-framework/operator-sdk#6230]
#### What did you do?

I followed all the steps to the t of the golang tutorial. I copied the memcached_controller.go file [https://github.com/operator-framework/operator-sdk/blob/latest/testdata/go/v3/memcached-operator/controllers/memcached_controller.go](url)
Then I pushed the operand image to personal dockerhub. I also tried to push to Google Artifact Registry.

In the "Run the operator" section, I tried option 2 "Run as a deployment inside the cluster". 
`make deploy IMG="crichessill/operator-sdk:v0.0.1"`

#### What did you expect to see?

I was expecting the deployment for the controller manager to come up successfully with 2 pods in running
`NAME                                                     READY   STATUS             RESTARTS      AGE
memcached-operator-controller-manager-57645b6bdd-b5zhv   1/2     CrashLoopBackOff   5 (30s ago)   5m15s`

#### What did you see instead? Under which circumstances?

When I print the logs of the pod, I see this error message

```
I1222 17:31:26.160239       1 request.go:601] Waited for 1.02709722s due to client-side throttling, not priority and fairness, request: GET:https://10.10.21.1:443/apis/constraints.gatekeeper.sh/v1alpha1?timeout=32s
1.6717302866172154e+09  INFO    controller-runtime.metrics      Metrics server is starting to listen    {"addr": "127.0.0.1:8080"}
1.6717302866179814e+09  INFO    setup   starting Sanmanager
1.6717302866184514e+09  INFO    Starting server {"path": "/metrics", "kind": "metrics", "addr": "127.0.0.1:8080"}
1.6717302866185534e+09  INFO    Starting server {"kind": "health probe", "addr": "[::]:8081"}
I1222 17:31:26.619020       1 leaderelection.go:248] attempting to acquire leader lease memcached-operator-system/86f835c3.example.com...
I1222 17:31:42.337981       1 leaderelection.go:258] successfully acquired lease memcached-operator-system/86f835c3.example.com
1.6717303023390703e+09  INFO    Starting EventSource    {"controller": "memcached", "controllerGroup": "cache.example.com", "controllerKind": "Memcached", "source": "kind source: *v1alpha1.Memcached"}
1.6717303023391252e+09  INFO    Starting EventSource    {"controller": "memcached", "controllerGroup": "cache.example.com", "controllerKind": "Memcached", "source": "kind source: *v1.Deployment"}
1.6717303023391435e+09  INFO    Starting Controller     {"controller": "memcached", "controllerGroup": "cache.example.com", "controllerKind": "Memcached"}
1.6717303023394394e+09  DEBUG   events  memcached-operator-controller-manager-57645b6bdd-b5zhv_0ff46ae8-12f9-45bb-852c-d6cfd2ca8f9e became leader        {"type": "Normal", "object": {"kind":"Lease","namespace":"memcached-operator-system","name":"86f835c3.example.com","uid":"c353257e-b0f5-4b56-ae23-03fb6958554c","apiVersion":"coordination.k8s.io/v1","resourceVersion":"185555397"}, "reason": "LeaderElection"}
1.6717303024412365e+09  INFO    Starting workers        {"controller": "memcached", "controllerGroup": "cache.example.com", "controllerKind": "Memcached", "worker count": 1}
1.6717303024415665e+09  INFO    Performing Finalizer Operations for Memcached before delete CR  {"controller": "memcached", "controllerGroup": "cache.example.com", "controllerKind": "Memcached", "Memcached": {"name":"memcached-sample","namespace":"memcached-operator-system"}, "namespace": "memcached-operator-system", "name": "memcached-sample", "reconcileID": "d26bb4f9-1ca8-4372-8549-8ac569c90f56"}
1.6717303024507546e+09  INFO    Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference{"controller": "memcached", "controllerGroup": "cache.example.com", "controllerKind": "Memcached", "Memcached": {"name":"memcached-sample","namespace":"memcached-operator-system"}, "namespace": "memcached-operator-system", "name": "memcached-sample", "reconcileID": "d26bb4f9-1ca8-4372-8549-8ac569c90f56"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1399867]

goroutine 222 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x14d6ca0, 0x2359d30})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/example/memcached-operator/controllers.(*MemcachedReconciler).doFinalizerOperationsForMemcached(0xc0001c7140, 0xc000434b40)
        /workspace/controllers/memcached_controller.go:300 +0xa7
github.com/example/memcached-operator/controllers.(*MemcachedReconciler).Reconcile(0xc0001c7140, {0x18d54f8, 0xc000551380}, {{{0xc00068c360?, 0x10?}, {0xc000492120?, 0x40dae7?}}})
        /workspace/controllers/memcached_controller.go:156 +0x158a
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x18d5450?, {0x18d54f8?, 0xc000551380?}, {{{0xc00068c360?, 0x15d98e0?}, {0xc000492120?, 0x4045d4?}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00037eb40, {0x18d5450, 0xc000027980}, {0x1526f40?, 0xc000346c20?})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320 +0x33c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00037eb40, {0x18d5450, 0xc000027980})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:230 +0x333
```
#### Environment

**Operator type:**

language go : go version go1.19.4 linux/amd64

**Kubernetes cluster type:**

Googke Kubernetes Engine: 1.22.15-gke.100

`$ operator-sdk version`

operator-sdk version: "v1.26.0"

`$ go version` (if language is Go)

go1.19.4
`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.15-gke.100", GitCommit:"4262ac74f84d8f8ec8f692ea2080483e932554f9", GitTreeState:"clean", BuildDate:"2022-09-22T09:24:03Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by varshaprasad96** [comment]
This seems to be a segmentation error caused by null pointer. Most of the time this error is caused when the logger is not instantiated properly when the reconciler starts. You can take a look at this issue (https://github.com/operator-framework/operator-sdk/issues/4966) to check if it is a similar case.

**Comment by scotRinga-MayaDog** [comment]
Sorry..trying to release something. Had it confused..

**Comment by sanmaym** [comment]
Ok. That might be it. I reviewed my code and I didnt have this line of code [https://github.com/operator-framework/operator-sdk/blob/v1.3.0/testdata/go/v3/memcached-operator/controllers/memcached_controller.go#L60](url). Thank you for your help.
